services:
  web:
    image: ghcr.io/zmaniacz/lfstats-web:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgres://lfstats:${DB_PASSWORD}@host.docker.internal:5432/lfstats"
      AUTH_TRUST_HOST: "true"
      AUTH_URL: "https://modern.lfstats.com"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    command: --label-enable --cleanup --interval 120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./watchtower-config.json:/config.json:ro
